### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by novacrazy** [szhublox/ambw-comfy#1]
```
Traceback (most recent call last):
  File "F:\sd\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\sd\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\sd\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\sd\ComfyUI\custom_nodes\ambw_comfyui\__init__.py", line 141, in ambw
    self.ratios[block] = self.search(block, 0.5, 0.5, 1, (0.5, 0))[0]
  File "F:\sd\ComfyUI\custom_nodes\ambw_comfyui\__init__.py", line 99, in search
    score = self.search(block, current + test_step, start, depth + 1,
  File "F:\sd\ComfyUI\custom_nodes\ambw_comfyui\__init__.py", line 91, in search
    self.merge(block, current)
  File "F:\sd\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\sd\ComfyUI\custom_nodes\ambw_comfyui\__init__.py", line 61, in merge
    sd1[key].copy_(sd1[key] * (1 - ratio) + sd2[key] * ratio)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by szhublox** [comment]
What's your workflow like? I can't replicate this on any vram settings. That said, it's probably a bug with this, i just don't know how to get it

**Comment by szhublox** [comment]
~~Well i just gave it a go and it gives garbage models now. Just euler noise. I guess he ldm changes have done something horrible to this repo. Wonder what that's about~~ fixed that but didn't figure out this issue report

**Comment by novacrazy** [comment]
I just used a fresh workflow with two models and the "Auto Merge Block Weighted" node, that's all. I have the realtime previews on, which shows it does generate an image, then fails in the `merge` function. Even if I set the two checkpoints to be the same, it still gives that error, so it's not something with f16/f32 conflicts. My main.py arguments are just `--windows-standalone-build --preview-method auto`

For what it's worth, I've noticed other model merging nodes (even the built-in ones) have been giving garbage as well, but I figured that was just because I didn't know how to properly weigh them, hence reaching for this node.

**Comment by OracleToes** [comment]
I got this error as well, pretty much the same setup. It's weird because this node used to work.
