### ISSUE TITLE
Error todo with expecting tensors to be on the same device 

### ISSUE THREAD

**Issue by Melodycloudu** [szhublox/ambw-comfy#5]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "F:\AITOOLS\ComfyUI\execution.py", line 151, in recursive_execute                     | 0/25 [00:00<?, ?block/s]
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\AITOOLS\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\AITOOLS\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\AITOOLS\ComfyUI\custom_nodes\ambw_comfyui\__init__.py", line 143, in ambw
    self.ratios[block] = self.search(block, 0.5, 0.5, 1, (0.5, 0))[0]
  File "F:\AITOOLS\ComfyUI\custom_nodes\ambw_comfyui\__init__.py", line 100, in search
    score = self.search(block, current + test_step, start, depth + 1,
  File "F:\AITOOLS\ComfyUI\custom_nodes\ambw_comfyui\__init__.py", line 92, in search
    self.merge(block, current)
  File "C:\Users\SirHo\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\AITOOLS\ComfyUI\custom_nodes\ambw_comfyui\__init__.py", line 62, in merge
    sd1[key].copy_(sd1[key] * (1 - ratio) + sd2[key] * ratio)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by dchatel** [comment]
The readme is misleading. It says running comfy with --highvram is **recommended** but it's not, it's **required**.
